# Generated by Django 3.2.9 on 2022-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('moderator_id', models.AutoField(db_column='Moderator_id', primary_key=True, serialize=False)),
                ('moderator_name', models.CharField(db_column='Moderator_name', max_length=15)),
                ('age', models.CharField(db_column='Age', max_length=5)),
                ('qualification', models.CharField(db_column='Qualification', max_length=10)),
                ('email_id', models.CharField(db_column='Email_id', max_length=20)),
                ('category', models.CharField(db_column='Category', max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'moderator',
                'managed': False,
            },
        ),
    ]
